# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"r\n\x10\x45mojiKitchenData\x12\x1b\n\x06\x65mojis\x18\x01 \x03(\x0b\x32\x0b.EmojiEntry\x12\"\n\x0c\x63ombinations\x18\x02 \x03(\x0b\x32\x0c.Combination\x12\x1d\n\ncategories\x18\x03 \x03(\x0b\x32\t.Category\"\'\n\nEmojiEntry\x12\r\n\x05\x65moji\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"0\n\x0b\x43ombination\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\temoji_ids\x18\x02 \x03(\rB\x02\x10\x01\"0\n\x08\x43\x61tegory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0estart_emoji_id\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMBINATION'].fields_by_name['emoji_ids']._loaded_options = None
  _globals['_COMBINATION'].fields_by_name['emoji_ids']._serialized_options = b'\020\001'
  _globals['_EMOJIKITCHENDATA']._serialized_start=16
  _globals['_EMOJIKITCHENDATA']._serialized_end=130
  _globals['_EMOJIENTRY']._serialized_start=132
  _globals['_EMOJIENTRY']._serialized_end=171
  _globals['_COMBINATION']._serialized_start=173
  _globals['_COMBINATION']._serialized_end=221
  _globals['_CATEGORY']._serialized_start=223
  _globals['_CATEGORY']._serialized_end=271
# @@protoc_insertion_point(module_scope)
